name: Generate ODC + Sync to SharePoint

on:
  push:
    branches: [main]
    paths:
      - 'src/generate.py'
      - 'src/odc_writer.py'

  workflow_dispatch:

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run generator
        run: |
          python -m src.generate

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Authenticate with SharePoint
        env:
          SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
          SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
          SHAREPOINT_TENANT_ID: ${{ secrets.SHAREPOINT_TENANT_ID }}
        run: |
          if [ -z "$SHAREPOINT_CLIENT_ID" ] || [ -z "$SHAREPOINT_CLIENT_SECRET" ] || [ -z "$SHAREPOINT_TENANT_ID" ]; then
            echo "❌ One or more SharePoint secrets are missing. Aborting."
            exit 1
          fi
      
          echo "🔐 Requesting access token from Microsoft Graph..."
          TOKEN_RESPONSE=$(curl -s -X POST \
            -d "grant_type=client_credentials" \
            -d "client_id=${SHAREPOINT_CLIENT_ID}" \
            -d "client_secret=${SHAREPOINT_CLIENT_SECRET}" \
            -d "scope=https://graph.microsoft.com/.default" \
            "https://login.microsoftonline.com/${SHAREPOINT_TENANT_ID}/oauth2/v2.0/token")
      
          ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')
          ERROR_MESSAGE=$(echo "$TOKEN_RESPONSE" | jq -r '.error.message')

          if [ "$ACCESS_TOKEN" == "null" ] || [ -z "$ACCESS_TOKEN" ]; then
            echo "❌ Failed to retrieve access token."
            echo "Error message: $ERROR_MESSAGE"
            echo "Full token response:"
            echo "$TOKEN_RESPONSE"
            exit 1
          fi
      
          echo "✅ Access token acquired."
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Delete old SharePoint folder
        env:
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
        run: |
          DRIVE_ID="b!CbtYWrofwUGBJWnaJkNwoNrBLp_kC3RKklSXPwrdeP3yH8_qmH9xT5Y6RODPNfYI"
          FOLDER_PATH="/General/Excel-Qualer-SDK"
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X DELETE \
            "https://graph.microsoft.com/v1.0/drives/$DRIVE_ID/root:$FOLDER_PATH" \
            -H "Authorization: Bearer $ACCESS_TOKEN")

          if [ "$RESPONSE" -ne 204 ]; then
            echo "❌ Failed to delete folder. HTTP status: $RESPONSE"
            echo "Response body:"
            cat response.json
            exit 1
          fi

          echo "✅ Folder deleted successfully."

      - name: Upload new Excel-Qualer-SDK
        env:
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
        run: |
          DRIVE_ID="b!CbtYWrofwUGBJWnaJkNwoNrBLp_kC3RKklSXPwrdeP3yH8_qmH9xT5Y6RODPNfYI"
          LOCAL_DIR="Excel-Qualer-SDK"
          REMOTE_DIR="/General/Excel-Qualer-SDK"

          find "$LOCAL_DIR" -type f | while read FILE; do
            RELATIVE_PATH="${FILE#$LOCAL_DIR/}"
            ESCAPED_PATH=$(echo "$RELATIVE_PATH" | sed 's/ /%20/g')
            TARGET_URL="https://graph.microsoft.com/v1.0/drives/$DRIVE_ID/root:$REMOTE_DIR/$ESCAPED_PATH:/content"

            echo "Uploading $FILE → $REMOTE_DIR/$ESCAPED_PATH"
            RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X PUT "$TARGET_URL" \
              -H "Authorization: Bearer $ACCESS_TOKEN" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @"$FILE")

            if [ "$RESPONSE" -ne 201 ]; then
              echo "❌ Failed to upload $FILE. HTTP status: $RESPONSE"
              echo "Response body:"
              cat response.json
              exit 1
            fi

            echo "✅ Uploaded $FILE successfully."
          done
